/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import forms.listaElev;
import forms.nyRegisterElev;




/**
 *
 * @author Firas & Joel
 */
public class adminSida extends javax.swing.JFrame {

    /**
     * Creates new form teacherSida
     */
    public adminSida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bakgrund = new javax.swing.JPanel();
        bakKnap = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setMinimumSize(new java.awt.Dimension(1042, 736));
        setResizable(false);
        getContentPane().setLayout(null);

        bakgrund.setBackground(new java.awt.Color(102, 102, 102));
        bakgrund.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        bakgrund.setMaximumSize(new java.awt.Dimension(1067, 736));
        bakgrund.setMinimumSize(new java.awt.Dimension(1067, 736));
        bakgrund.setPreferredSize(new java.awt.Dimension(1067, 736));

        bakKnap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bakKnap.setText("Tillbaka");
        bakKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakKnapActionPerformed(evt);
            }
        });

        combobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nyregistrera elever", "ändra all information om enskild elev", "ta bort elever ur systemet", "nyregistrera lärare", "ge andra lärare administratörsstatus", "ändra information om lärare", "ta bort lärare ur systemet", "registrera huspoäng", "dra av huspoäng", "nyregistrera kurser", "ändra information om kurser", "ta bort kurser", "ändra information om vilken elev som är elevhemsprefekt", "ändra information om vilken lärare som är elevhemsföreståndare", "registrera nya elevhem", "ta ut statistik över betyg baserat på enskilda elevhem", "ta ut statistik över betyg baserat på enskilda lärare" }));
        combobox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboboxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Administratör sida");

        javax.swing.GroupLayout bakgrundLayout = new javax.swing.GroupLayout(bakgrund);
        bakgrund.setLayout(bakgrundLayout);
        bakgrundLayout.setHorizontalGroup(
            bakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bakgrundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bakKnap)
                .addGap(107, 107, 107))
            .addGroup(bakgrundLayout.createSequentialGroup()
                .addGroup(bakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bakgrundLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1))
                    .addGroup(bakgrundLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 373, Short.MAX_VALUE))
        );
        bakgrundLayout.setVerticalGroup(
            bakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bakgrundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(bakKnap)
                .addGap(91, 91, 91))
        );

        getContentPane().add(bakgrund);
        bakgrund.setBounds(0, 0, 1060, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bakKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakKnapActionPerformed
        // TODO add your handling code here:
        new StartSida().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bakKnapActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void comboboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboboxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        selectCombo();
    }//GEN-LAST:event_comboboxPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminSida().setVisible(true);
            }
        });
    }

    
    public void selectCombo(){
    int nr = combobox.getSelectedIndex();
    if(nr==0){
        nyRegisterElev nre= new nyRegisterElev();
          nre.setVisible(true);
    }if(nr==1){
        listaElev ls= new listaElev();
        ls.setVisible(true); 
    }
    
    
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakKnap;
    private javax.swing.JPanel bakgrund;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
