package hogwarts;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;






/**
 *
 * @author Firas & Joel
 */
public class adminLogin extends javax.swing.JFrame {

    

    

    /**
     * Creates new form HogSkola
    
     */
    public adminLogin() {
        initComponents();
        
        
    }





  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elevSida = new javax.swing.JButton();
        studentText = new javax.swing.JLabel();
        larareText = new javax.swing.JLabel();
        larareSida = new javax.swing.JButton();
        rubriktext1 = new javax.swing.JLabel();
        adminSida = new javax.swing.JButton();
        adminText = new javax.swing.JLabel();
        adminID = new javax.swing.JLabel();
        adminUser = new javax.swing.JTextField();
        adminLosenord = new javax.swing.JLabel();
        adminPass = new javax.swing.JPasswordField();
        adminLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1042, 736));
        setSize(new java.awt.Dimension(1042, 736));
        getContentPane().setLayout(null);

        elevSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\min sida.jpg")); // NOI18N
        elevSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevSidaActionPerformed(evt);
            }
        });
        getContentPane().add(elevSida);
        elevSida.setBounds(740, 250, 240, 197);

        studentText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentText.setForeground(new java.awt.Color(0, 255, 255));
        studentText.setText("Student");
        getContentPane().add(studentText);
        studentText.setBounds(820, 450, 110, 30);

        larareText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        larareText.setForeground(new java.awt.Color(153, 255, 0));
        larareText.setText("Lärare");
        getContentPane().add(larareText);
        larareText.setBounds(480, 450, 76, 30);

        larareSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\lärare.jpg")); // NOI18N
        larareSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larareSidaActionPerformed(evt);
            }
        });
        getContentPane().add(larareSida);
        larareSida.setBounds(400, 250, 240, 197);

        rubriktext1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 60)); // NOI18N
        rubriktext1.setText("Välkommen till Hogwarts Skola");
        getContentPane().add(rubriktext1);
        rubriktext1.setBounds(60, 0, 910, 90);

        adminSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\kontakt.jpg")); // NOI18N
        adminSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSidaActionPerformed(evt);
            }
        });
        getContentPane().add(adminSida);
        adminSida.setBounds(70, 250, 240, 197);

        adminText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminText.setForeground(new java.awt.Color(255, 0, 0));
        adminText.setText("Admin");
        getContentPane().add(adminText);
        adminText.setBounds(150, 450, 76, 30);

        adminID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adminID.setForeground(new java.awt.Color(255, 204, 0));
        adminID.setText("Admin ID");
        getContentPane().add(adminID);
        adminID.setBounds(80, 500, 150, 20);

        adminUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(adminUser);
        adminUser.setBounds(80, 520, 213, 28);

        adminLosenord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adminLosenord.setForeground(new java.awt.Color(255, 204, 0));
        adminLosenord.setText("Lösenord:");
        getContentPane().add(adminLosenord);
        adminLosenord.setBounds(80, 550, 100, 20);

        adminPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(adminPass);
        adminPass.setBounds(80, 570, 213, 28);

        adminLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adminLogin.setText("Logga in");
        adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(adminLogin);
        adminLogin.setBounds(80, 610, 110, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\header.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1100, 736));
        jLabel1.setMinimumSize(new java.awt.Dimension(1060, 736));
        jLabel1.setPreferredSize(new java.awt.Dimension(1060, 736));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginActionPerformed
try {
    Class.forName("org.firebirdsql.jdbc.FBDriver");
    java.sql.Connection con=DriverManager.getConnection("jdbc:firebirdsql:localhost/3050:/db/HOGDB.FDB", "sysdba", "masterkey");
    java.sql.Statement stmt=con.createStatement();
    String DBQ="Select * from LARARE where FORNAMN='"+adminUser.getText()+"' and LOSENORD= '"+adminPass.getText()+"'";
    
    ResultSet rs=stmt.executeQuery(DBQ);
    if(rs.next())
    {   
        JOptionPane.showMessageDialog(null, "inloggning lyckades");
         //skapa new jframe
          adminSida sida= new adminSida();
          sida.setVisible(true);
          this.dispose();
    }
         
          else
        JOptionPane.showMessageDialog(null, "inloggning fel");

}
catch(HeadlessException | ClassNotFoundException | SQLException e){

}
    }//GEN-LAST:event_adminLoginActionPerformed
   
    private void larareSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larareSidaActionPerformed
        // TODO add your handling code here:
        new larareLogin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_larareSidaActionPerformed

    private void adminSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSidaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_adminSidaActionPerformed

    private void elevSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevSidaActionPerformed
        // TODO add your handling code here:
        new elevSida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_elevSidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminID;
    private javax.swing.JButton adminLogin;
    private javax.swing.JLabel adminLosenord;
    private javax.swing.JPasswordField adminPass;
    private javax.swing.JButton adminSida;
    private javax.swing.JLabel adminText;
    private javax.swing.JTextField adminUser;
    private javax.swing.JButton elevSida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton larareSida;
    private javax.swing.JLabel larareText;
    private javax.swing.JLabel rubriktext1;
    private javax.swing.JLabel studentText;
    // End of variables declaration//GEN-END:variables
}
