package hogwarts;

import oru.inf.InfDB;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Firas & Joel
 */
public class StartSida extends javax.swing.JFrame {
    

    /**
     * Creates new form HogSkola
     */
    public StartSida() {
        initComponents();
        
        
    }

    /**
     *
     * @param hogdb
     */
    public StartSida(InfDB hogdb) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elevSida = new javax.swing.JButton();
        studentText = new javax.swing.JLabel();
        larareText = new javax.swing.JLabel();
        larareSida = new javax.swing.JButton();
        rubriktext1 = new javax.swing.JLabel();
        adminSida = new javax.swing.JButton();
        adminText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1042, 736));
        setSize(new java.awt.Dimension(1042, 736));
        getContentPane().setLayout(null);

        elevSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\min sida.jpg")); // NOI18N
        elevSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevSidaActionPerformed(evt);
            }
        });
        getContentPane().add(elevSida);
        elevSida.setBounds(740, 250, 240, 197);

        studentText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentText.setForeground(new java.awt.Color(0, 255, 255));
        studentText.setText("Student");
        getContentPane().add(studentText);
        studentText.setBounds(820, 450, 110, 30);

        larareText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        larareText.setForeground(new java.awt.Color(153, 255, 0));
        larareText.setText("Lärare");
        getContentPane().add(larareText);
        larareText.setBounds(480, 450, 76, 30);

        larareSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\lärare.jpg")); // NOI18N
        larareSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larareSidaActionPerformed(evt);
            }
        });
        getContentPane().add(larareSida);
        larareSida.setBounds(400, 250, 240, 197);

        rubriktext1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 60)); // NOI18N
        rubriktext1.setText("Välkommen till Hogwarts Skola");
        getContentPane().add(rubriktext1);
        rubriktext1.setBounds(60, 0, 910, 90);

        adminSida.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\elev sida bilder\\kontakt.jpg")); // NOI18N
        adminSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSidaActionPerformed(evt);
            }
        });
        getContentPane().add(adminSida);
        adminSida.setBounds(70, 250, 240, 197);

        adminText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminText.setForeground(new java.awt.Color(255, 0, 0));
        adminText.setText("Admin");
        getContentPane().add(adminText);
        adminText.setBounds(150, 450, 76, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT\\Desktop\\Systemvetenskap\\delkurs 4\\Final project\\pictures\\header.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1100, 736));
        jLabel1.setMinimumSize(new java.awt.Dimension(1060, 736));
        jLabel1.setPreferredSize(new java.awt.Dimension(1060, 736));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSidaActionPerformed
        // TODO add your handling code here:
        new adminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminSidaActionPerformed

    private void larareSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larareSidaActionPerformed
        // TODO add your handling code here:
        new larareLogin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_larareSidaActionPerformed

    private void elevSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevSidaActionPerformed
        // TODO add your handling code here:
        new elevSida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_elevSidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartSida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminSida;
    private javax.swing.JLabel adminText;
    private javax.swing.JButton elevSida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton larareSida;
    private javax.swing.JLabel larareText;
    private javax.swing.JLabel rubriktext1;
    private javax.swing.JLabel studentText;
    // End of variables declaration//GEN-END:variables
}
